arm64: provide own memcpy for pie
Got the following error trying to compile this with clang-3.6 on arm64:

>   GEN      criu/pie/restorer.built-in.bin.o
> criu/pie/native.lib.a(parasite-vdso.o): In function `vdso_proxify':
> /criu/criu/pie/parasite-vdso.c:132: undefined reference to `memcpy'

This happens because clang emits a call to memcpy for struct
initialization (specifically, struct vdso_symtable in vdso_proxify()).

See commit 214e280 ("pie: provide own memcpy for x86") for more
background info about the issue.

Cc: Christopher Covington <cov@codeaurora.org>
Cc: Dmitry Safonov <dsafonov@virtuozzo.com>
Signed-off-by: Kir Kolyshkin <kir@openvz.org>