compel ppc64 infect.c: fix clang compilation
This is generated by clang-3.8:
> compel/arch/ppc64/src/lib/infect.c:31:20: error: unused function
> '__check_code_syscall' [-Werror,-Wunused-function]
> static inline void __check_code_syscall(void)
>                    ^

The fix is the same as in commit 3ea2fd7.

Signed-off-by: Kir Kolyshkin <kir@openvz.org>