fpu00 test: fix for clang
clang complains a number of times on our inline asm code, like this:

> fpu00.c:13:6: error: ambiguous instructions require an explicit suffix
> (could be 'flds', 'fldl', or 'fldt')
>                           "fld  %0\n"
>                           ^
> <inline asm>:1:2: note: instantiated into assembly here
>         fld     -4(%rsp)
>         ^

As floats are used, the suffix should be 's' ("short", 32-bit, float).

Add it where needed.

Signed-off-by: Kir Kolyshkin <kir@openvz.org>