inotify_system tests: fix for clang
When compiling with clang, it complains like this:

> clang -g -O2 -Wall -Werror -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=0  -iquote ../lib/arch/x86/include -I../lib   inotify_system.c ../lib/libzdtmtst.a ../lib/libzdtmtst.a -o inotify_system
> inotify_system.c:323:50: error: comparison of unsigned expression < 0 is always false [-Werror,-Wtautological-compare]
>         if ((common_desc.inot < 0) || (common_desc.file < 0) || \
>                                        ~~~~~~~~~~~~~~~~ ^ ~
> inotify_system.c:324:21: error: comparison of unsigned expression < 0 is always false [-Werror,-Wtautological-compare]
>                         (common_desc.dir < 0) || (common_desc.link < 0)) {
>                          ~~~~~~~~~~~~~~~ ^ ~
> inotify_system.c:324:47: error: comparison of unsigned expression < 0 is always false [-Werror,-Wtautological-compare]
>                         (common_desc.dir < 0) || (common_desc.link < 0)) {
>                                                   ~~~~~~~~~~~~~~~~ ^ ~
> 3 errors generated.

Indeed these fields are uint32_t. As they are used to store the results of
inotify_init() and inotify_add_watch() function calls, the type should be int.

Signed-off-by: Kir Kolyshkin <kir@openvz.org>